* Can I afford to spend $_______ right now?
** TODO Overview
   Coming soon...
** Setup
*** Add environment keys
   gzo_api_key: <%= ENV["GZO_API_KEY"] %>
   gzo_cust_id: <%= ENV["GZO_CUST_ID"] %>
   gzo_domain: <%= ENV["GZO_DOMAIN"] %>
   gzo_user_id: <%= ENV["GZO_USER_ID"] %>
** Planned Features
*** Answer should be more nuanced
- :no
  "Definitely"
- :maybe_no
  "Probably not"
- :maybe_yes
  "All things being equal, yes."
- :yes
  "Yes! (As far as I can tell)"
*** Display reaction gif based on answer
:)
*** Parameterize variables
**** Minimum account balance
**** Risk adverse multiplier
** Thoughts
*** Cash flow vs statistical analysis of transactions
In reality, this should be based on historical data or at least
historical data should be checked to validate the reality of a
cash-flow based decision. If your cash flow for the past 6-12 months
has been completely dissonant with actuality, the decision should
reflect this.

Alternatively, the cash flow could simply be generated or seeded based
on historical data, and the software would continue to work as
is. However, this requires that the user has enough transactions on
which to perform statistical analysis.
*** Optionally show -why- you can't afford it
Show the cashflow bill that will cause the account balance to go below
min-acct-bal threshold.

Also potentially show which cashflow income would cause the account
balance to go back above the min-acct-bal threshold, and how long that
would take.
*** Visually show how your weekly cashflow account balance changes
