# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b8fdf2f76da7d8452aa7757387bb69c07c5797cd5f1319bdfe60fac40824d93b251b4cf31d8bbc8067ebf5a73ea3e40bc2e98c35171ab0550ebcb1067cfdff88
  gzo_api_key: <%= ENV["GZO_API_KEY"] %>
  gzo_cust_id: <%= ENV["GZO_CUST_ID"] %>
  gzo_domain: <%= ENV["GZO_DOMAIN"] %>
  gzo_user_id: <%= ENV["GZO_USER_ID"] %>

test:
  secret_key_base: fe7c120cfb4c9ad117a54833630d3d903f6c60b31a6b548fe56bfa4afcefd59cc9dc74315822f36c213afd0c5263e02c4759956090402d721ddcff1cfd768671
  gzo_api_key: <%= ENV["GZO_API_KEY"] %>
  gzo_cust_id: <%= ENV["GZO_CUST_ID"] %>
  gzo_domain: <%= ENV["GZO_DOMAIN"] %>
  gzo_user_id: <%= ENV["GZO_USER_ID"] %>


# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  gzo_api_key: <%= ENV["GZO_API_KEY"] %>
  gzo_cust_id: <%= ENV["GZO_CUST_ID"] %>
  gzo_domain: <%= ENV["GZO_DOMAIN"] %>
  gzo_user_id: <%= ENV["GZO_USER_ID"] %>
